
version: '3.7'
services:
  load-balancer:
    image: traefik:1.7-alpine
    restart: always
    command:
      - "--api"
      - "--docker"
      - "--ping"
    networks:
      - default
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  node-app:
    build: ./node-app
    labels:
      - "traefik.backend=node-app"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:localhost"
    environment:
      - NODE_ENV=development
      - SENT=sentinel
      - SENTPORT=26379
      - SITE_VERSION=v1.0
      - SITE_NAME=Cloud Team Example App
    command: npm start

  master:
    image: redis:3
  slave:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master
  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave

networks:
  default:
